#!/bin/bash
extract_image() {
  mkdir -p /var/tmp/${BUILD_ID}
  tar -C /var/tmp/${BUILD_ID} -xf -
}

prep_siphon() {
  curl \
    -k \
    -f \
    -o /dev/null \
    --progress-bar \
    -H "X-Auth-Token: ${WAREHOUSE_TOKEN}" \
    -d "{\"old-id\": \"${PREVIOUS_BUILD_ID}.tgz\", \"new-id\": \"${BUILD_ID}.tgz\"}" \
    "https://${WAREHOUSE_IP}:1566/stages"
}

create_ssh_key() {
  if [[ ! -f /var/tmp/id_rsa ]]
  then
    ssh-keygen -t rsa -N "" -f /var/tmp/id_rsa
  fi
}

rsync_image() {
  rsync \
    -a \
    --delete \
    -e 'ssh -p 1567 -i /var/tmp/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' \
    /var/tmp/${BUILD_ID}/ \
    ${BUILD_ID}.tgz@${WAREHOUSE_IP}:${BUILD_ID}.tgz
}

commit_siphon() {
  curl \
    -k \
    -f \
    --progress-bar \
    -o /dev/null \
    -H "X-Auth-Token: ${WAREHOUSE_TOKEN}" \
    -X PUT \
    "https://${WAREHOUSE_IP}:1566/stages/${BUILD_ID}.tgz"
}

gzip_image() {
  gzip > /var/tmp/${BUILD_ID}.tgz
}

upload_image() {
  curl \
    -k \
    -f \
    --progress-bar \
    -o /dev/null \
    -H "X-Auth-Token: ${WAREHOUSE_TOKEN}" \
    --data-binary @/var/tmp/${BUILD_ID}.tgz \
    "https://${WAREHOUSE_IP}:7410/blobs/${BUILD_ID}.tgz"
}

fetch_image() {
  curl \
    -k \
    -f \
    -H "X-Auth-Token: ${WAREHOUSE_TOKEN}" \
    https://${WAREHOUSE_IP}:7410/blobs/${BUILD_ID}.tgz \
  | gunzip --stdout
}

usage() {
  cat <<-END
The forklift project has two executables: lift and drop.

lift - upload a docker image to the warehouse

drop - retrieve a docker image from the warehouse

example usage:

docker run --rm -i nanobox/forklift drop build_id=1234 warehouse_token=abcd warehouse_ip=1.2.3.4 | docker import

docker export ubuntu | docker run --rm -i nanobox/forklift lift build_id=1234 warehouse_token=abcd warehouse_ip=1.2.3.4

docker export ubuntu | docker run --rm -i nanobox/forklift lift build_id=1234 previous_build_id=2345 warehouse_token=abcd warehouse_ip=1.2.3.4
END
}